export const CHANGE_TALHAO_NOME = "CHANGE_TALHAO_NOME";
export const CHANGE_TALHAO_VARIEDADE = "CHANGE_TALHAO_VARIEDADE";
export const CHANGE_TALHAO_AREA = "CHANGE_TALHAO_AREA";
export const CHANGE_TALHAO_DATA = "CHANGE_TALHAO_DATA";
export const CHANGE_LOGIN_EMAIL = "CHANGE_LOGIN_EMAIL";
export const CHANGE_LOGIN_PASSWORD = "CHANGE_LOGIN_PASSWORD";

export const DATA_TABLE_INSERT = "DATA_TABLE_INSERT";
export const DATA_TABLE_DELETE = "DATA_TABLE_DELETE";

export const CHANGE_FAZENDA_NOME = "CHANGE_FAZENDA_NOME";
export const CHANGE_FAZENDA_CNPJ = "CHANGE_FAZENDA_CNPJ";
export const CHANGE_FAZENDA_IE = "CHANGE_FAZENDA_IE";
export const CHANGE_FAZENDA_END = "CHANGE_FAZENDA_END";
export const CHANGE_FAZENDA_BAIRRO = "CHANGE_FAZENDA_BAIRRO";
export const CHANGE_FAZENDA_COMP = "CHANGE_FAZENDA_COMP";
export const CHANGE_FAZENDA_CEP = "CHANGE_FAZENDA_CEP";
export const CHANGE_FAZENDA_COORDENADAS = "CHANGE_FAZENDA_COORDENADAS";
export const CHANGE_FAZENDA_TEL = "CHANGE_FAZENDA_TEL";
export const CHANGE_FAZENDA_PROPIETARIO = "CHANGE_FAZENDA_PROPIETARIO";
