export const CHANGE_TALHAO_NOME = "CHANGE_TALHAO_NOME";
export const CHANGE_TALHAO_VARIEDADE = "CHANGE_TALHAO_VARIEDADE";
export const CHANGE_TALHAO_AREA = "CHANGE_TALHAO_AREA";
export const CHANGE_TALHAO_DATA = "CHANGE_TALHAO_DATA";
export const CHANGE_LOGIN_EMAIL = "CHANGE_LOGIN_EMAIL";
export const CHANGE_LOGIN_PASSWORD = "CHANGE_LOGIN_PASSWORD";

export const DATA_TABLE_INSERT = "DATA_TABLE_INSERT";
export const DATA_TABLE_DELETE = "DATA_TABLE_DELETE";
